language: go
sudo: false
go:
  - 1.9.3
  - "1.10"
  - tip

script:
  - go test -v -covermode=count -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - curl -sL https://git.io/goreleaser | bash
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/go-push-light-*.zip
    - dist/go-push-light-*.tar.bz2
    - dist/go-push-light-*.sha256
  skip_cleanup: true
  on:
    tags: true
    repo: nikepan/go-push-light
    condition: $TRAVIS_GO_VERSION =~ ^1\.9\.[0-9]+$
